# Generated by Django 4.0.6 on 2022-07-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Maintenance', 'Maintenance'), ('Research', 'Research'), ('Test', 'Test')], max_length=24),
        ),
    ]
